In [1]:
import polars as pl
from sqlalchemy import create_engine

In [2]:
uri = "postgresql://p8:p8@localhost:5433/meteoforecast"

In [15]:
# --- xlsx ---

df_ichtegem = pl.read_database_uri("SELECT * FROM raw.weather_ichtegem", uri)
df_la_madeleine = pl.read_database_uri("SELECT * FROM raw.weather_la_madeleine", uri)

# --- json (non deplier) ---

df_infoclimat = pl.read_database_uri("SELECT * FROM raw.infoclimat", uri)
df_meteo = pl.read_database_uri("SELECT * FROM raw.open_meteo_roubaix", uri)

In [16]:
df_ichtegem.describe()

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ _airbyte_ ┆ _airbyte_ ┆ _airbyte_ ┆ … ┆ Dew_Point ┆ Temperatu ┆ Precip__R ┆ Precip__ │
│ ---       ┆ raw_id    ┆ extracted ┆ meta      ┆   ┆ ---       ┆ re        ┆ ate_      ┆ Accum_   │
│ str       ┆ ---       ┆ _at       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ ---       ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1899      ┆ 1899      ┆ 1899      ┆ … ┆ 1899      ┆ 1899      ┆ 1899      ┆ 1899     │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2026-07-1 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 8 15:01:2 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 0.945760+ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 00:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ min       ┆ 019f75bf- ┆ 2026-07-1 ┆ {"changes ┆ … ┆ 36.0 °F   ┆ 36.5 °F   ┆ 0.00 in   ┆ 0.00 in  │
│           ┆ 0ce6-7382 ┆ 8 15:01:2 ┆ ":[],"syn ┆   ┆           ┆           ┆           ┆          │
│           ┆ -adb1-032 ┆ 0+00:00   ┆ c_id":8}  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 640…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2026-07-1 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 8 15:01:2 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 0+00:00   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2026-07-1 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 8 15:01:2 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 1+00:00   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2026-07-1 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 8 15:01:2 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 2+00:00   ┆           ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 019f75bf- ┆ 2026-07-1 ┆ {"changes ┆ … ┆ 58.0 °F   ┆ 66.4 °F   ┆ 0.35 in   ┆ 0.18 in  │
│           ┆ 157f-7e60 ┆ 8 15:01:2 ┆ ":[],"syn ┆   ┆           ┆           ┆           ┆          │
│           ┆ -9be4-442 ┆ 2+00:00   ┆ c_id":8}  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 53a…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
def renseigne(df): # Fonction de profiling adapter à polars
    n = df.height
    nulls = df.null_count().row(0)
    profil = pl.DataFrame({
        'colonne': df.columns, 
        'type':[str(t)for t in df.dtypes],
        'longueur_max':[df[c].cast(pl.Utf8).str.len_chars().max() for c in df.columns],
        'non_null':[n - x for x in nulls],
        'nan':list(nulls),
        "% nan": [round(x / n * 100, 2) for x in nulls],
        'valeur_unique':[df[c].n_unique()for c in df.columns]
    })
    return profil

#cols_airbnb = renseigne(df) # Instance le df profilé
# cols_airbnb.write_csv('../docs/cols_airbnb.csv') # Produit un csv du profil
#display(cols_airbnb) # Affiche le résultat de la fonctioin de profiling

In [ ]:
df_ichtegem.columns

['_airbyte_raw_id',
 '_airbyte_extracted_at',
 '_airbyte_meta',
 '_airbyte_generation_id',
 'UV',
 'Gust',
 'Time',
 'Wind',
 'Solar',
 'Speed',
 'Humidity',
 'Pressure',
 'Dew_Point',
 'Temperature',
 'Precip__Rate_',
 'Precip__Accum_']

In [19]:
df_la_madeleine.columns

['_airbyte_raw_id',
 '_airbyte_extracted_at',
 '_airbyte_meta',
 '_airbyte_generation_id',
 'UV',
 'Gust',
 'Time',
 'Wind',
 'Solar',
 'Speed',
 'Humidity',
 'Pressure',
 'Dew_Point',
 'Temperature',
 'Precip__Rate_',
 'Precip__Accum_']

In [14]:
renseigne(df_ichtegem)

shape: (16, 7)
┌─────────────────────┬────────────────────┬──────────────┬──────────┬─────┬───────┬───────────────┐
│ colonne             ┆ type               ┆ longueur_max ┆ non_null ┆ nan ┆ % nan ┆ valeur_unique │
│ ---                 ┆ ---                ┆ ---          ┆ ---      ┆ --- ┆ ---   ┆ ---           │
│ str                 ┆ str                ┆ i64          ┆ i64      ┆ i64 ┆ f64   ┆ i64           │
╞═════════════════════╪════════════════════╪══════════════╪══════════╪═════╪═══════╪═══════════════╡
│ _airbyte_raw_id     ┆ String             ┆ 36           ┆ 1908     ┆ 0   ┆ 0.0   ┆ 1908          │
│ _airbyte_extracted_ ┆ Datetime(time_unit ┆ 32           ┆ 1908     ┆ 0   ┆ 0.0   ┆ 3             │
│ at                  ┆ ='us', time_…      ┆              ┆          ┆     ┆       ┆               │
│ _airbyte_meta       ┆ String             ┆ 26           ┆ 1908     ┆ 0   ┆ 0.0   ┆ 1             │
│ _airbyte_generation ┆ Int64              ┆ 1            ┆ 1908     ┆ 0   ┆ 0.0   ┆ 1             │
│ _id                 ┆                    ┆              ┆          ┆     ┆       ┆               │
│ UV                  ┆ Decimal(precision= ┆ 12           ┆ 1908     ┆ 0   ┆ 0.0   ┆ 5             │
│                     ┆ 38, scale=10…      ┆              ┆          ┆     ┆       ┆               │
│ …                   ┆ …                  ┆ …            ┆ …        ┆ …   ┆ …     ┆ …             │
│ Pressure            ┆ String             ┆ 8            ┆ 1908     ┆ 0   ┆ 0.0   ┆ 70            │
│ Dew_Point           ┆ String             ┆ 7            ┆ 1908     ┆ 0   ┆ 0.0   ┆ 180           │
│ Temperature         ┆ String             ┆ 7            ┆ 1908     ┆ 0   ┆ 0.0   ┆ 242           │
│ Precip__Rate_       ┆ String             ┆ 7            ┆ 1908     ┆ 0   ┆ 0.0   ┆ 8             │
│ Precip__Accum_      ┆ String             ┆ 7            ┆ 1908     ┆ 0   ┆ 0.0   ┆ 14            │
└─────────────────────┴────────────────────┴──────────────┴──────────┴─────┴───────┴───────────────┘

In [8]:
df_infoclimat.schema

Schema([('_airbyte_raw_id', String),
        ('_airbyte_extracted_at', Datetime(time_unit='us', time_zone='UTC')),
        ('_airbyte_meta', String),
        ('_airbyte_generation_id', Int64),
        ('data', String),
        ('errors', String),
        ('hourly', String),
        ('status', String),
        ('metadata', String),
        ('stations', String)])

In [ ]:
import json
mesures = json.loads(df_infoclimat["hourly"][0])["07015"]   # tableau de mesures
df_i = pl.DataFrame(mesures) 
renseigne(df_i)

shape: (15, 7)
┌────────────────┬────────┬──────────────┬──────────┬─────┬───────┬───────────────┐
│ colonne        ┆ type   ┆ longueur_max ┆ non_null ┆ nan ┆ % nan ┆ valeur_unique │
│ ---            ┆ ---    ┆ ---          ┆ ---      ┆ --- ┆ ---   ┆ ---           │
│ str            ┆ str    ┆ i64          ┆ i64      ┆ i64 ┆ f64   ┆ i64           │
╞════════════════╪════════╪══════════════╪══════════╪═════╪═══════╪═══════════════╡
│ dh_utc         ┆ String ┆ 19           ┆ 60       ┆ 0   ┆ 0.0   ┆ 60            │
│ humidite       ┆ String ┆ 3            ┆ 60       ┆ 0   ┆ 0.0   ┆ 28            │
│ id_station     ┆ String ┆ 5            ┆ 60       ┆ 0   ┆ 0.0   ┆ 1             │
│ nebulosite     ┆ String ┆ 1            ┆ 60       ┆ 0   ┆ 0.0   ┆ 4             │
│ neige_au_sol   ┆ Null   ┆ null         ┆ 0        ┆ 60  ┆ 100.0 ┆ 1             │
│ …              ┆ …      ┆ …            ┆ …        ┆ …   ┆ …     ┆ …             │
│ temps_omm      ┆ String ┆ 2            ┆ 9        ┆ 51  ┆ 85.0  ┆ 5             │
│ vent_direction ┆ String ┆ 3            ┆ 60       ┆ 0   ┆ 0.0   ┆ 18            │
│ vent_moyen     ┆ String ┆ 4            ┆ 60       ┆ 0   ┆ 0.0   ┆ 7             │
│ vent_rafales   ┆ String ┆ 4            ┆ 60       ┆ 0   ┆ 0.0   ┆ 13            │
│ visibilite     ┆ String ┆ 5            ┆ 60       ┆ 0   ┆ 0.0   ┆ 29            │
└────────────────┴────────┴──────────────┴──────────┴─────┴───────┴───────────────┘

In [20]:
df_ichtegem["Time"].head(10)

shape: (10,)
Series: 'Time' [str]
[
	"00:04:00"
	"00:09:00"
	"00:14:00"
	"00:19:00"
	"00:24:00"
	"00:29:00"
	"00:34:00"
	"00:39:00"
	"00:44:00"
	"00:49:00"
]

In [21]:
df_ichtegem["Time"].n_unique()

291

In [23]:
df_la_madeleine["Time"].to_list()[268:278]

['22:24:00',
 '22:29:00',
 '22:34:00',
 '22:39:00',
 '22:44:00',
 '22:49:00',
 '22:54:00',
 '22:59:00',
 '23:04:00',
 '23:09:00']